### ISSUE TITLE
Create wbstack logo for use on the site, and use it

### ISSUE THREAD

**Issue by addshore** [wbstack/ui#94]

**Comment by GreenReaper** [comment]
Maybe rather than create one, WBStack could use one that was developed already, but not used? This seems to be how Wikibase got it's logo, of which there were many [unused variations](https://commons.wikimedia.org/wiki/File:Wikidata_logo_proposal_variation_2.svg) ("other versions" has more); and if that's a little too close to Wikibase's own (maybe more suitable for the "taster" project?) there are [others submitted for Wikidata](https://meta.wikimedia.org/wiki/Wikidata/Logo_voting#Voting), some of which look stack-y.

[This one](https://meta.wikimedia.org/wiki/File:Wikidata_logo_cells_white_bg.svg) seems pretty on the money without being overly linked to the classic database logo - it could represent many related, similar units - either the items in the database, or wikis in the stack. It also happens to be created by [a certain MW developer and podcaster](https://www.mediawiki.org/wiki/User:Yaron_Koren) who has a hand in two semantic wiki projects, so it'd be amusing to add something on the Wikibase side.

[This one](https://meta.wikimedia.org/wiki/File:20120409_wikidata10.svg) is artistic and communicates a number of topics (which might cover various hobbies if that is a road travelled by the project), although is hard to grasp except at higher resolution. It was [popular in voting](https://meta.wikimedia.org/wiki/User:Denny_Vrande%C4%8Di%C4%87_(WMDE)/Logo_voting) - but it perhaps doesn't scream "technological project".

Other than that, what *should* the logo communicate? What's the target audience? Is it important to reference the tools that form part of the stack; the federation with other wikis; or the way that you have a separate-but-equal wiki with a bunch of items?

[A logo can change over time](https://logos.fandom.com/wiki/Fandom) - like a name, as projects evolve - but it'd help to know where you want to go.

**Comment by addshore** [comment]
This one does look quite stacky.
https://meta.wikimedia.org/wiki/File:Wikidata_logo_cells_white_bg.svg
Could be good to use for inspiration
