### ISSUE TITLE
Add UI configuration for Lexeme

### ISSUE THREAD

**Issue by addshore** [wbstack/ui#96]
Will need https://github.com/wbstack/api/issues/43

**Comment by GreenReaper** [comment]
To have Special:NewLexeme fully usable, I think it'll be necessary to be able to set $wgLexemeLanguageCodePropertyId to a custom property ID. This is used to extract the ISO 639-1 two-letter language code from the item selected as language by the user. By default it is null, so a valid code must be entered manually after selecting an item as the lexeme's language. Wikis using federated properties should presumably have it set to [P218](https://www.wikidata.org/wiki/Property:P218).

There's also $wbLexemeEnableDataTransclusion, which [gates exposure](https://github.com/wikimedia/mediawiki-extensions-WikibaseLexeme/blob/REL1_35/src/WikibaseLexemeHooks.php#L381) to Scribunto functions relating to lexemes within [mw.wikibase.lexeme[.entity.lexeme]](https://github.com/wikimedia/mediawiki-extensions-WikibaseLexeme/blob/REL1_35/docs/lua.wiki). It's false by default, probably because the interface is not stable (and maybe not complete).

**Comment by addshore** [comment]
All deployed
